# Generated by Django 4.2.5 on 2023-09-07 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_procedures', to=settings.AUTH_USER_MODEL),
        ),
    ]
